<?php
/**
 * Implements hook_block_info().
 */
function ybzx_block_info() {
	$blocks = array();
  //Introduce of this sites on user/* page .when not login.
  $blocks['love_group_index'] = array(
    'info' => t('love_group_index'),
    'cache' => DRUPAL_NO_CACHE, //to be confirmed
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'node/2',
  );
  $blocks['love_group_index_bottom'] = array(
    'info' => 'love_group_index_bottom',
    'cache' => DRUPAL_NO_CACHE, //to be confirmed
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'node/2',
  );
  $blocks['love_group_index_bottom_rule'] = array(
    'info' => 'love_group_index_bottom_rule',
    'cache' => DRUPAL_NO_CACHE, //to be confirmed
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'node/2',
  );
  $blocks['love_group_index_bottom_who'] = array(
    'info' => 'love_group_index_bottom_who',
    'cache' => DRUPAL_NO_CACHE, //to be confirmed
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'node/2',
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ybzx_block_view($delta = '') {
	module_load_include('inc', 'love_layout', 'love_layout.block');
  $block = array();
  switch ($delta) {
    case 'love_group_index_bottom':
      $block['subject'] = NULL;
      $block['content'] = ' <h3>永不止息の规则:</h3>
        <p class="index_bottom">只接受熟人间邮箱邀请注册，请为您邀请的肢体祷告，您在熟人之间互相介绍时，应慎重，严谨，并为之代祷。</p> ';
      break;
    case 'love_group_index_bottom_rule':
      $block['subject'] = NULL;
      $block['content'] = '
        <h3>源于2013.11.11:</h3>
        <p class="index_bottom">@bluesky_still透过对当前教会单身肢体需求的看见，业余时间开发的针对主内肢体婚恋社交网站，通过简洁的关系建立渠道，熟人的推荐，舆论监督与指导，为肢体提供一个便捷互相了解、信实互动的社交平台。</p>';
      break;
    case 'love_group_index_bottom_who':
      $block['subject'] = NULL;
      $block['content'] = '<div class="bottom-copyright">
          <ul>
            <li>'.l('关于我们','about').'</li> ┊ 
            <li>'.l('联系我们','about').'</li> ┊ 
            <li>'.l('常见问题','questions').'</li> ┊ 
            <li>'.l('意见反馈','node/485').'</li>
          </ul>
          <p>Copyright © 2013 - 2014 永不止息 版权所有 </p>
        </div>';
      break;
    case 'love_group_index':
      global $user;
      if(!$user->uid){
        $button = '<button type="button" class="btn btn-success btn-lg download-btn" data-toggle="modal" data-target="#click-down">
    <span class="glyphicon glyphicon-user"></span> '.l('注册申请','qa/register').'
  </button>';
      }else{
         $button = '<button type="button" class="btn btn-success btn-lg download-btn" data-toggle="modal" data-target="#click-down">
    <span class="glyphicon glyphicon-edit"></span> '.l('完善资料','user/register').'
  </button>';
      }

      if(og_is_member('node', 2)){
        $button = '
  <button type="button" class="btn btn-success btn-lg download-btn" data-toggle="modal" data-target="#click-down">
    <span class="glyphicon glyphicon-ok"></span> '.l('审核通过','photos').'
  </button>';
      }
      $block['subject'] = NULL;
      $block['content'] = '<div class="intro-left pull-left">
  <h2>幸福家庭</h2>
  <h3>从婚恋迈出第一步</h3>
  <h3>响应呼召，组建家庭 让爱永不止息！</h3>'.$button.'

  <div class="version"> <h3>永不止息の异象:</h3>
  <p>爱是互相激励、共同成长，并且需要公众见证、公开交往，接受监督的，让更多的肢体在婚恋交友，及组建家庭上彰显神的荣耀。</p></div>
</div> ';
      break;
  	
  	default:
  		# code...
  		break;
  }
  return $block;
}

// This function adds a '+' next to each datebox with a link to the event node creation page,
// if the current user has permission to create events.
// Replace 'mymodule' with the name of your module.
// Replace 'event' with the name of your CCK content type.
function ybzx_preprocess_calendar_datebox(&$vars) {
  global $user;
  $content_types = array('grace365','in_him');
  $types = node_type_get_types();
  foreach ($content_types as $key => $content_type) {
    $last_node = _ybzx_get_last_node($content_type);
    $now = date('d',time());
    if(isset($last_node)) {
      $last = date('d',$last_node->created);
    }else{
      $last = $now -1;
    }
    if($vars['day'] == $now && $now - $last >= 1) {
      if (user_access('create '.$content_type.' content', $user)) {
          $vars['add_content_links'][] = l('+'.$types[$content_type]->name, 'node/add/'.str_replace('_', '-', $content_type));        
        }
    }  
  }
  
}

function  _ybzx_get_last_node($content_type = 'article') {// get latest node.
  $query = "SELECT n.nid nid, n.created created FROM {node} n  WHERE n.type = :type order by n.created desc limit 0,1";
  return db_query($query, array(':type' => $content_type))->fetch();
}


function ybzx_get_default_image_field_value($bundle = 'grace365', $field_name = 'field_image', $type = 'default_image', $entity_type = 'node') {
  $query = db_select('field_config_instance', 'fc');
  $query->fields('fc', array('id'));
  $query->condition('field_name', $field_name,'=');
  $query->condition('bundle', $bundle,'=');
  $query->condition('entity_type', $entity_type,'=');
  $id = $query->execute()->fetchField();

  $query = db_select('file_usage', 'fu');
  $query->fields('fu', array('fid'));
  $query->condition('type', $type,'=');
  $query->condition('id', $id,'=');
  $fid = $query->execute()->fetchField();
  $img = file_load($fid);
  
  $img = $img->uri;
  $img = file_create_url($img);
  return $img;
}



/**
* $type = news nodes
**/

function ybzx_get_nodes($content_type = 'article', $counts = 1, $type = 'news') {
  
  $query = db_select('node', 'n');
  $query->fields('n', array('nid'));
  $query->condition('n.status', 1,'=');
  $query->condition('n.type', $content_type,'=');
  $query->orderBy('n.created', 'DESC');
  $query->range(0, $counts);
  $results = $query->execute()->fetchAll();

  $default_image = ybzx_get_default_image_field_value($content_type, $field_name = 'field_image', $content_type = 'default_image', $entity_type = 'node');
  $second_image = 'http://wx.dev.camplus.hk/sites/default/files/pictures/picture-172-1356487827.jpg';
  
  $nodes = array();
  $news = array();
  if(count($results))
    foreach ($results as $key => $value) {
      $node = node_load($value->nid);
      $nodes[] = $node;
      
      $des = check_markup($node->body[LANGUAGE_NONE][0]['value']);//decode_entities()
      // $des = strip_tags($des);
      // $des = str_replace('&nbsp;&nbsp;',"\n",$des);
      // $des = str_replace('&nbsp;',' ',$des);
      // $des = truncate_utf8($des, 300, $wordsafe = FALSE, $add_ellipsis = TRUE, $min_wordsafe_length = 1);

      if($node->field_image) {
        $default_uri = $node->field_image[LANGUAGE_NONE][0]['uri'];
        $default_image = file_create_url($default_uri);
      }
      $img = array(
          'Title'=> $node->title,
          'Description'=>$des,
          'PicUrl'=>$default_image,
          'Url'=> url(NULL, array('absolute' => TRUE)) . (variable_get('clean_url', 0) ? '' : '?q=').'node/'.$node->nid,
        );
      $news[] = $img;
      // return $news;
    }
    return $$type;
}
///////////////////////////////////////////////
//////////////  LOVE2in1 begin  ///////////////
///////////////////////////////////////////////

///////////////////报名参加文字修改begin/////////////////////////////
/**
 * Implement hook_field_formatter_info().
 */
function ybzx_field_formatter_info() {
  return array(
    'og_group_subscribe' => array(
      'label' => t('OG subscribe link'),
      'field types' => array('list_boolean'),
      'settings' => array(
        'field_name' => FALSE,
      ),
    ),
    'og_list_default' => array(
      'label' => t('OG audience list'),
      'field types' => array('entityreference'),
    ),
  );
}


/**
 * Implements hook_field_formatter_view().
 */
function ybzx_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  global $user;
  $settings = $display['settings'];

  switch ($display['type']) {
    case 'og_group_subscribe':
      $account = clone $user;
      if (!og_is_group($entity_type, $entity)) {
        return;
      }

      if (!empty($entity->uid) && ($entity->uid == $account->uid)) {
        // User is the group manager.
        $element[0] = array(
          '#type' => 'html_tag',
          '#tag' => 'span',
          '#attributes' => array('title' => '您是活动发起人', 'class' => 'group manager'),
          '#value' => '您是活动发起人',
        );

        return $element;
      }

      list($id,, $bundle) = entity_extract_ids($entity_type, $entity);
      if (og_is_member($entity_type, $id, 'user', $account, array(OG_STATE_ACTIVE, OG_STATE_PENDING))) {
        if (og_user_access($entity_type, $id, 'unsubscribe', $account)) {
          $links['title'] = t('Unsubscribe from group');
          $links['href'] = "group/$entity_type/$id/unsubscribe";
          $links['class'] = 'group unsubscribe';
        }
      }
      else {
        if (og_is_member($entity_type, $id, 'user', $account, array(OG_STATE_BLOCKED))) {
          // If user is blocked, they should not be able to apply for
          // membership.
          return;
        }

        // Check if user can subscribe to the field.
        if (empty($settings['field_name']) && $audience_field_name = og_get_best_group_audience_field('user', $account, $entity_type, $bundle)) {
          $settings['field_name'] = $audience_field_name;
        }
        if (!$settings['field_name']) {
          return;
        }

        $field_info = field_info_field($settings['field_name']);

        // Check if entity is referencable.
        if ($field_info['settings']['target_type'] != $entity_type) {
          // Group type doesn't match.
          return;
        }
        if (!empty($field_info['settings']['handler_settings']['target_bundles']) && !in_array($bundle, $field_info['settings']['handler_settings']['target_bundles'])) {
          // Bundles don't match.
          return;
        }

        if (!og_check_field_cardinality('user', $account, $settings['field_name'])) {
          $element[0] = array(
            '#type' => 'html_tag',
            '#tag' => 'span',
            '#attributes' => array('title' => format_plural($field_info['cardinality'], 'You are already registered to another group', 'You are already registered to @count groups'), 'class' => 'group other'),
            '#value' => format_plural($field_info['cardinality'], 'You are already registered to another group', 'You are already registered to @count groups'),
          );
          return $element;
        }

        $url = "group/$entity_type/$id/subscribe";
        if ($settings['field_name']) {
          $url .= '/' . $settings['field_name'];
        }

        if (og_user_access($entity_type, $id, 'subscribe without approval', $account)) {
          $links['title'] = t('Subscribe to group');
          $links['class'] = 'group subscribe';
          if ($account->uid) {
            $links['href'] = $url;
          }
          else {
            $links['href'] = 'user/login';
            $links['options'] = array('query' => array('destination' => $url));
          }
        }
        elseif (og_user_access($entity_type, $id, 'subscribe')) {
          $links['title'] = t('Request group membership');
          if($entity->type == 'event') $links['title'] = '报名参加';
          $links['class'] = 'group subscribe request';
          if ($account->uid) {
            $links['href'] = $url;
          }
          else {
            $links['href'] = 'user/login';
            $links['options'] = array('query' => array('destination' => $url));
          }
        }
        else {
          $element[0] = array(
            '#type' => 'html_tag',
            '#tag' => 'span',
            '#attributes' => array('title' => t('This is a closed group. Only a group administrator can add you.'), 'class' => 'group closed'),
            '#value' => t('This is a closed group. Only a group administrator can add you.'),
          );

          return $element;
        }
      }

      if (!empty($links['title'])) {
        $links += array('options' => array('attributes' => array('title' => $links['title'], 'class' => array($links['class']))));
        $element[0] = array(
          '#type' => 'link',
          '#title' => $links['title'],
          '#href' => $links['href'],
          '#options' => $links['options'],
        );
        return $element;
      }
      // User didn't have permissions.
      break;

    case 'og_list_default':
      $accessible_ids = array();
      $private = FALSE;
      $wrapper = entity_metadata_wrapper($entity_type, $entity);
      $field_name = $field['field_name'];
      if (!$wrapper->{$field_name}->value()) {
        return;
      }
      if ($field['cardinality'] == 1) {
        // Single-value field.
        if ($wrapper->{$field_name}->entityAccess('view')) {
          $id = $wrapper->{$field_name}->getIdentifier();
          $accessible_ids[$id] = TRUE;
        }
        else {
          $private = TRUE;
        }
      }
      else {
        // Multi-value field.
        foreach ($wrapper->{$field_name} as $wrapper_field) {
          $id = $wrapper_field->value(array('identifier' => TRUE));
          if ($wrapper_field->entityAccess('view')) {
            $accessible_ids[$id] = TRUE;
          }
          else {
            $private = TRUE;
          }
        }
      }

      if ($entity_type == 'user') {
        // Show only the groups a user is active in.
        foreach ($wrapper->{$field_name . '__og_membership'}->value() as $og_membership) {
          if ($og_membership->state != OG_STATE_ACTIVE) {
            unset($accessible_ids[$og_membership->gid]);
          }
        }
      }
      $group_type = $field['settings']['target_type'];
      $accessible_entity = entity_load($group_type, array_keys($accessible_ids));
      $element = array();
      foreach ($items as $delta => $item) {
        if (!empty($accessible_ids[$item['target_id']]) && !empty($accessible_entity[$item['target_id']])) {
          $wrapper = entity_metadata_wrapper($group_type, $item['target_id']);
          $element[$delta] = array(
            '#type' => 'link',
            '#title' => $wrapper->label(),
            '#href' => $wrapper->url->value(),
            // Add the group type and group ID, so it's easier for implementing
            // modules to extend the formatter.
            '#group_type' => $group_type,
            '#gid' => $wrapper->getIdentifier(),
          );
        }
      }
      if ($private) {
        $count = count($element);
        $delta = $count == 0 ? 0 : $count + 1;
        $element[$delta] = array('#markup' => '- ' . t('Private group') . ' -');
      }

      return $element;
  }
}

///////////////////报名参加文字修改end/////////////////////////////